//ExportHeader.java - emit a C header with a prototype for every function
//@category Delinker
//
// Usage: -postScript ExportHeader <outFile>

import ghidra.app.script.GhidraScript;

import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.FunctionSignature;
import ghidra.program.model.listing.Program;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.ParameterDefinition;

import java.io.File;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

public class ExportHeader extends GhidraScript {

    private static final int MAX_PARAMS = 12;

    /**
     * Ghidra's demangler leaves internal data types like "/Demangler/DName" in
     * signatures; those are not valid C. Fall back to int for anything unsafe.
     */
    private static String safeType(DataType dt) {
        if (dt == null) {
            return "int";
        }
        String t = dt.getName();
        if (t == null) {
            return "int";
        }
        t = t.trim();
        if (t.isEmpty() || t.indexOf('/') >= 0 || t.indexOf('(') >= 0) {
            return "int";
        }
        // Allow plain identifiers, "unsigned int", "struct Foo", and trailing '*'.
        if (t.matches("[A-Za-z_][A-Za-z0-9_]*(\\s*\\*+)*")
                || t.matches("(unsigned|signed|const|long|short)\\s+[A-Za-z_][A-Za-z0-9_]*(\\s*\\*+)*")
                || t.matches("(struct|union|enum)\\s+[A-Za-z_][A-Za-z0-9_]*(\\s*\\*+)*")) {
            return t;
        }
        return "int";
    }

    @Override
    public void run() throws Exception {
        final Program program = getCurrentProgram();
        String[] args = getScriptArgs();
        String out = args.length > 0 ? args[0] : "C:\\th12_funcs.h";

        List<String> decls = new ArrayList<>();
        List<String> cxx = new ArrayList<>();
        FunctionIterator it = program.getFunctionManager().getFunctions(true);
        int skipped = 0;
        while (it.hasNext()) {
            Function f = it.next();
            if (f.isExternal() || f.getBody().getNumAddresses() == 0) {
                continue;
            }
            String name = f.getName();
            // Skip C++-mangled / demangled-with-'::' names: they need real headers.
            if (!name.matches("[A-Za-z_][A-Za-z0-9_]*")) {
                cxx.add(name);
                continue;
            }
            FunctionSignature sig = f.getSignature();
            String conv = sig.getCallingConventionName();
            // __thiscall is a C++-only keyword that will not parse in a .c file.
            // On x86 it passes this in ECX and the first argument in EDX, which
            // is exactly __fastcall's register usage.
            if ("__thiscall".equals(conv) || "_vectorcall".equals(conv)) {
                conv = "__fastcall";
            }
            StringBuilder sb = new StringBuilder();
            sb.append(safeType(sig.getReturnType()));
            sb.append(' ');
            if (conv != null && !conv.isEmpty() && !conv.equals("unknown")) {
                sb.append(conv).append(' ');
            }
            else {
                // Ghidra usually models x86 as __cdecl; this game is __fastcall.
                sb.append("__fastcall ");
            }
            sb.append(name).append('(');
            ParameterDefinition[] params = sig.getArguments();
            if (params == null || params.length == 0) {
                sb.append("void");
            }
            else {
                for (int i = 0; i < params.length && i < MAX_PARAMS; i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    DataType dt = params[i].getDataType();
                    sb.append(safeType(dt)).append(" a").append(i);
                }
            }
            sb.append(");");
            decls.add(sb.toString());
        }
        decls.sort(String::compareTo);
        cxx.sort(String::compareTo);

        File f = new File(out);
        if (f.getParentFile() != null) {
            f.getParentFile().mkdirs();
        }
        try (PrintWriter w = new PrintWriter(f, StandardCharsets.UTF_8.name())) {
            w.println("/* Generated by Ghidra from th12.exe - do not edit by hand. */");
            w.println("#ifndef TH12_FUNCS_H");
            w.println("#define TH12_FUNCS_H");
            w.println();
            w.println("typedef unsigned int  uint32;");
            w.println("typedef unsigned short uint16;");
            w.println("typedef unsigned char  uint8;");
            w.println("typedef signed char    int8;");
            w.println("typedef short          int16;");
            w.println("typedef int            int32;");
            w.println("typedef unsigned int   size_t_;");
            w.println("typedef int            BOOL;");
            w.println("typedef float          f32;");
            w.println("typedef double         f64;");
            w.println("typedef void*          ptr;");
            w.println();
            w.println("#ifdef __cplusplus");
            w.println("extern \"C\" {");
            w.println("#endif");
            for (String d : decls) {
                w.println(d);
            }
            w.println("#ifdef __cplusplus");
            w.println("}");
            w.println("#endif");
            w.println();
            w.println("#endif");
        }
        println("[hdr] wrote " + decls.size() + " C prototype(s) to " + out
                + "; skipped " + skipped + ", cxx-named " + cxx.size());
        try (PrintWriter w = new PrintWriter(new File(out + ".cxxlist"),
                StandardCharsets.UTF_8.name())) {
            for (String c : cxx) {
                w.println(c);
            }
        }
    }
}
