/* Generated by scripts\gen_types.py - do not edit by hand.
 *
 * Ghidra's decompilation names types that windows.h, d3d9.h, dinput.h and
 * the CRT do not declare. Every one of them is an error in the
 * translation unit, and the same handful accounts for most of the
 * corpus failing to compile:
 *
 *   C2065  identifier undefined                       e.g. undefined4
 *   C2440  cannot convert from 'int' to 'undefined4'
 *   C2036  'CatchGuardRN *' : unknown size
 *   C2079  uses undefined struct 'undefined4'
 *
 * None of these is a per-function mistake. Declaring the names once,
 * here, is what makes the difference. Each is given the size Ghidra
 * implies, because pointer arithmetic and sizeof need one; and a
 * recovered structure gets a single placeholder byte, since the
 * decompilation never accesses a member through these names and the
 * real layout is not known anyway.
 */

#ifndef TH12_GHIDRA_H
#define TH12_GHIDRA_H

#include <stddef.h>
#include <wchar.h>

/* Ghidra's scalar names. Every one of these is a complete type: that is
 * what keeps `*(undefined4 *)(p + n)` from being C2036. */
typedef unsigned short   undefined;
typedef unsigned char    undefined1;
typedef unsigned short   undefined2;
typedef unsigned int     undefined4;
typedef unsigned __int64 undefined8;
typedef unsigned char    uchar;
typedef char             sbyte;
typedef unsigned short   word;
typedef short            sword;
typedef unsigned int     dword;
typedef int              sdword;
typedef unsigned __int64 qword;
typedef __int64          sqword;
typedef unsigned int     uint;
typedef int              sint;
typedef unsigned long    ulong;
typedef unsigned short   ushort;
typedef unsigned __int64 ulonglong;
typedef unsigned __int64 ulonglonglong;
typedef unsigned long    ushortlong;
typedef __int64          int64;
typedef unsigned __int64 uint64;
typedef __int64          longlong;
typedef long double      float10;
#ifndef __cplusplus
typedef unsigned char    bool;
#endif
typedef unsigned char    exception;
typedef unsigned char    INTRNCVT_STATUS;
typedef unsigned char    _LocaleUpdate;
typedef int              DName;
typedef int              DNameStatus;
typedef int              Tokens;
typedef unsigned __int64 __uint64;
typedef long double      unkbyte10;

/* No C type has these widths. A struct gives them a size so the
 * pointer arithmetic stays legal, and nothing in the decompilation
 * ever reads a member, so the contents do not matter. */
typedef struct undefined3 { unsigned char _[3]; } undefined3;
typedef struct undefined5 { unsigned char _[5]; } undefined5;
typedef struct undefined6 { unsigned char _[6]; } undefined6;
typedef struct undefined7 { unsigned char _[7]; } undefined7;
typedef struct int128 { unsigned char _[16]; } int128;
typedef struct uint3 { unsigned char _[3]; } uint3;

/* Structures Ghidra recovered a name for but no layout for. The
 * decompilation takes their address and does arithmetic on pointers to
 * them; it never reads a member, so one placeholder byte is enough to
 * make the type complete. `_ptiddata`, `_s_FuncInfo` and `_StartAddress`
 * are real examples; the leading underscore is why the old code's
 * `name[0].isupper()` test dropped them. `std` is a namespace, not a
 * C type, so it stays out. */
typedef struct CatchGuardRN                 { unsigned char _; } CatchGuardRN;
typedef struct DNameNode                    { unsigned char _; } DNameNode;
typedef struct DNameStatusNode              { unsigned char _; } DNameStatusNode;
typedef struct EHExceptionRecord            { unsigned char _; } EHExceptionRecord;
typedef struct EHRegistrationNode           { unsigned char _; } EHRegistrationNode;
typedef struct HeapManager                  { unsigned char _; } HeapManager;
typedef struct PCNZCH                       { unsigned char _; } PCNZCH;
typedef struct PCNZWCH                      { unsigned char _; } PCNZWCH;
typedef struct Replicator                   { unsigned char _; } Replicator;
typedef struct Studio                       { unsigned char _; } Studio;
typedef struct TranslatorGuardRN            { unsigned char _; } TranslatorGuardRN;
typedef struct UnDecorator                  { unsigned char _; } UnDecorator;
typedef struct __type_info_node             { unsigned char _; } __type_info_node;
typedef struct _func_4879                   { unsigned char _; } _func_4879;
typedef struct _func_char_ptr_long          { unsigned char _; } _func_char_ptr_long;
typedef struct _func_void_void_ptr          { unsigned char _; } _func_void_void_ptr;
typedef struct _s_CatchableType             { unsigned char _; } _s_CatchableType;
typedef struct _s_ESTypeList                { unsigned char _; } _s_ESTypeList;
typedef struct _s_FuncInfo                  { unsigned char _; } _s_FuncInfo;
typedef struct _s_HandlerType               { unsigned char _; } _s_HandlerType;
typedef struct _s_TryBlockMapEntry          { unsigned char _; } _s_TryBlockMapEntry;
typedef struct bad_alloc                    { unsigned char _; } bad_alloc;
typedef struct bad_exception                { unsigned char _; } bad_exception;
typedef struct bad_typeid                   { unsigned char _; } bad_typeid;
typedef struct pDNameNode                   { unsigned char _; } pDNameNode;
typedef struct pairNode                     { unsigned char _; } pairNode;
typedef struct pcharNode                    { unsigned char _; } pcharNode;

/* Ghidra names the corpus calls through. An opaque struct here
 * would make the call C2064, so each is a real function typedef. */
typedef void (__cdecl *_PHNDLR)(int);
typedef int (__cdecl _func_int_uint)(unsigned int);
typedef unsigned (__stdcall _StartAddress)(void *);

/* The SDK declares each of these as a bare tag but no typedef;
 * Ghidra used the bare name as a type. A self-typedef is only valid
 * for a tag, and gives the compiler the name it was asked for. */
typedef struct _CONTEXT _CONTEXT;
typedef enum _EXCEPTION_DISPOSITION _EXCEPTION_DISPOSITION;
typedef struct _EXCEPTION_POINTERS _EXCEPTION_POINTERS;
typedef struct _FILETIME _FILETIME;
typedef struct _PROCESS_INFORMATION _PROCESS_INFORMATION;
typedef struct _STARTUPINFOA _STARTUPINFOA;
typedef struct _WIN32_FIND_DATAA _WIN32_FIND_DATAA;
typedef struct __lc_time_data __lc_time_data;
typedef struct _cpinfo _cpinfo;
typedef struct joyinfoex_tag joyinfoex_tag;
typedef struct localeinfo_struct localeinfo_struct;
typedef struct tagMSG tagMSG;
typedef struct tagRECT tagRECT;
typedef struct threadmbcinfostruct threadmbcinfostruct;

/* Ghidra's name for a function pointer. */
typedef int (__cdecl *code)();

/* Names the decompilation uses that no header declares. `true` and
 * `false` alone are 197 of the corpus' undeclared-identifier errors:
 * a .c file built by VC9 in C mode has no `bool`, because
 * <stdbool.h> is C99 and this compiler predates the switch, yet
 * Ghidra writes the keywords either way. */
#ifndef true
#define true 1
#endif
#ifndef false
#define false 0
#endif
#ifndef MXCSR
#define MXCSR (*(unsigned int *)0)
#endif
#ifndef int3
#define int3 0xCC
#endif

#endif /* TH12_GHIDRA_H */
