/* Generated by scripts\gen_globals.py - do not edit by hand.
 *
 * Ghidra names a datum it could not type after its address - DAT_004b43cc
 * is the value at 0x004b43cc - and declares nothing for it. That leaves
 * C2065 'undeclared identifier' in every unit that touches one, which was
 * 524 of the 934 remaining errors and the largest single cause of the
 * corpus failing to build.
 *
 * Each type here is inferred from how the decompilation uses the name,
 * not from the file. Every address falls past .data's raw size, so the
 * on-disk bytes are the ones belonging to whatever section follows and
 * say nothing about the value. The usage is the evidence: a `+ '\x01'`
 * counter is a char, an xor against a stack address is the 4-byte
 * __security_cookie, and a name used as the base of `*(T *)(x + n)`
 * holds an address - the `n` there is a raw byte offset, so the name
 * itself stays an integer rather than a pointer type.
 *
 * A name no rule matched gets `undefined4`. That is the right default on
 * x86, and it is not a silent guess: a wrong width changes the emitted
 * code, which the byte comparison in scripts\splice.py reports as
 * not-exact rather than passing unnoticed.
 */

#ifndef TH12_GLOBALS_H
#define TH12_GLOBALS_H

extern int            DAT_00498334    ; /* 00498334 */
extern int            DAT_00498338    ; /* 00498338 */
extern int            DAT_00498354    ; /* 00498354 */
extern int            DAT_00498364    ; /* 00498364 */
extern int            DAT_0049836c    ; /* 0049836c */
extern int            DAT_0049855c    ; /* 0049855c */
extern int            DAT_00498764    ; /* 00498764 */
extern int            DAT_004993cc    ; /* 004993cc */
extern int            DAT_0049953c    ; /* 0049953c */
extern int            DAT_0049981c    ; /* 0049981c */
extern int            DAT_00499c6c    ; /* 00499c6c */
extern int            DAT_0049b88c    ; /* 0049b88c */
extern int            DAT_0049bcfc    ; /* 0049bcfc */
extern int            DAT_0049cd70    ; /* 0049cd70 */
extern int            DAT_0049cd88    ; /* 0049cd88 */
extern int            DAT_0049cda8    ; /* 0049cda8 */
extern int            DAT_0049d438    ; /* 0049d438 */
extern int            DAT_0049d5c8    ; /* 0049d5c8 */
extern int            DAT_0049d620    ; /* 0049d620 */
extern int            DAT_0049d640    ; /* 0049d640 */
extern int            DAT_0049dba8    ; /* 0049dba8 */
extern int            DAT_0049e758    ; /* 0049e758 */
extern int            DAT_0049e8d8    ; /* 0049e8d8 */
extern int            DAT_0049f2d8    ; /* 0049f2d8 */
extern int            DAT_0049f434    ; /* 0049f434 */
extern int            DAT_0049f4d8    ; /* 0049f4d8 */
extern int            DAT_0049f588    ; /* 0049f588 */
extern int            DAT_0049f6a8    ; /* 0049f6a8 */
extern int            DAT_0049f8b8    ; /* 0049f8b8 */
extern int            DAT_0049fb3c    ; /* 0049fb3c */
extern int            DAT_0049fe14    ; /* 0049fe14 */
extern int            DAT_0049fe19    ; /* 0049fe19 */
extern int            DAT_004a015c    ; /* 004a015c */
extern int            DAT_004a0174    ; /* 004a0174 */
extern int            DAT_004a01a0    ; /* 004a01a0 */
extern int            DAT_004a01a4    ; /* 004a01a4 */
extern int            DAT_004a01b4    ; /* 004a01b4 */
extern int            DAT_004a01bc    ; /* 004a01bc */
extern int            DAT_004a01ec    ; /* 004a01ec */
extern int            DAT_004a0280    ; /* 004a0280 */
extern int            DAT_004a02a8    ; /* 004a02a8 */
extern int            DAT_004a02e0    ; /* 004a02e0 */
extern int            DAT_004a092c    ; /* 004a092c */
extern int            DAT_004a0954    ; /* 004a0954 */
extern int            DAT_004a0a8c    ; /* 004a0a8c */
extern int            DAT_004a0acc    ; /* 004a0acc */
extern int            DAT_004a0b2c    ; /* 004a0b2c */
extern int            DAT_004a0b60    ; /* 004a0b60 */
extern int            DAT_004a0b94    ; /* 004a0b94 */
extern int            DAT_004a0bb0    ; /* 004a0bb0 */
extern int            DAT_004a0bd8    ; /* 004a0bd8 */
extern int            DAT_004a0bf8    ; /* 004a0bf8 */
extern int            DAT_004a0c20    ; /* 004a0c20 */
extern int            DAT_004a0c58    ; /* 004a0c58 */
extern int            DAT_004a0c78    ; /* 004a0c78 */
extern int            DAT_004a0c90    ; /* 004a0c90 */
extern int            DAT_004a0cb4    ; /* 004a0cb4 */
extern int            DAT_004a0cd8    ; /* 004a0cd8 */
extern int            DAT_004a0ee4    ; /* 004a0ee4 */
extern int            DAT_004a10d8    ; /* 004a10d8 */
extern int            DAT_004a12f0    ; /* 004a12f0 */
extern int            DAT_004a13b4    ; /* 004a13b4 */
extern int            DAT_004a13e8    ; /* 004a13e8 */
extern int            DAT_004a15a4    ; /* 004a15a4 */
extern int            DAT_004a1f94    ; /* 004a1f94 */
extern int            DAT_004a1fd8    ; /* 004a1fd8 */
extern int            DAT_004a20a8    ; /* 004a20a8 */
extern int            DAT_004a2334    ; /* 004a2334 */
extern int            DAT_004a2338    ; /* 004a2338 */
extern int            DAT_004a235c    ; /* 004a235c */
extern int            DAT_004a245c    ; /* 004a245c */
extern int            DAT_004a246c    ; /* 004a246c */
extern int            DAT_004a24cc    ; /* 004a24cc */
extern int            DAT_004a260c    ; /* 004a260c */
extern int            DAT_004a2664    ; /* 004a2664 */
extern int            DAT_004a269c    ; /* 004a269c */
extern int            DAT_004a26d4    ; /* 004a26d4 */
extern int            DAT_004a2700    ; /* 004a2700 */
extern int            DAT_004a272c    ; /* 004a272c */
extern int            DAT_004a2758    ; /* 004a2758 */
extern int            DAT_004a277c    ; /* 004a277c */
extern int            DAT_004a27a0    ; /* 004a27a0 */
extern int            DAT_004a27c0    ; /* 004a27c0 */
extern int            DAT_004a27e8    ; /* 004a27e8 */
extern int            DAT_004a2820    ; /* 004a2820 */
extern int            DAT_004a285c    ; /* 004a285c */
extern int            DAT_004a2870    ; /* 004a2870 */
extern int            DAT_004a2890    ; /* 004a2890 */
extern int            DAT_004a28e0    ; /* 004a28e0 */
extern int            DAT_004a2930    ; /* 004a2930 */
extern int            DAT_004a2984    ; /* 004a2984 */
extern int            DAT_004a29b4    ; /* 004a29b4 */
extern int            DAT_004a29d4    ; /* 004a29d4 */
extern int            DAT_004a2a04    ; /* 004a2a04 */
extern int            DAT_004a2a38    ; /* 004a2a38 */
extern int            DAT_004a2a60    ; /* 004a2a60 */
extern int            DAT_004a2e04    ; /* 004a2e04 */
extern int            DAT_004a2e34    ; /* 004a2e34 */
extern int            DAT_004a2e6c    ; /* 004a2e6c */
extern int            DAT_004a313c    ; /* 004a313c */
extern int            DAT_004a3160    ; /* 004a3160 */
extern int            DAT_004a32c4    ; /* 004a32c4 */
extern int            DAT_004a33b8    ; /* 004a33b8 */
extern int            DAT_004a33f4    ; /* 004a33f4 */
extern int            DAT_004a3418    ; /* 004a3418 */
extern int            DAT_004a3478    ; /* 004a3478 */
extern int            DAT_004a34bc    ; /* 004a34bc */
extern int            DAT_004a3570    ; /* 004a3570 */
extern int            DAT_004a45c0    ; /* 004a45c0 */
extern int            DAT_004a45c8    ; /* 004a45c8 */
extern int            DAT_004a54c0    ; /* 004a54c0 */
extern int            DAT_004a5e40    ; /* 004a5e40 */
extern int            DAT_004a5f70    ; /* 004a5f70 */
extern int            DAT_004a5f78    ; /* 004a5f78 */
extern int            DAT_004a5f80    ; /* 004a5f80 */
extern int            DAT_004a5f90    ; /* 004a5f90 */
extern int            DAT_004a5f98    ; /* 004a5f98 */
extern int            DAT_004a5fa0    ; /* 004a5fa0 */
extern int            DAT_004a5fb0    ; /* 004a5fb0 */
extern int            DAT_004a5fc0    ; /* 004a5fc0 */
extern int            DAT_004a5fc8    ; /* 004a5fc8 */
extern int            DAT_004a5fd0    ; /* 004a5fd0 */
extern int            DAT_004a5fe0    ; /* 004a5fe0 */
extern int            DAT_004a5ff0    ; /* 004a5ff0 */
extern int            DAT_004a5ff8    ; /* 004a5ff8 */
extern int            DAT_004a6000    ; /* 004a6000 */
extern int            DAT_004a6008    ; /* 004a6008 */
extern int            DAT_004a6010    ; /* 004a6010 */
extern int            DAT_004a6018    ; /* 004a6018 */
extern int            DAT_004a7610    ; /* 004a7610 */
extern int            DAT_004a7618    ; /* 004a7618 */
extern int            DAT_004a7620    ; /* 004a7620 */
extern int            DAT_004a7628    ; /* 004a7628 */
extern int            DAT_004a7eb0    ; /* 004a7eb0 */
extern int            DAT_004a7eb8    ; /* 004a7eb8 */
extern int            DAT_004a7ec0    ; /* 004a7ec0 */
extern int            DAT_004a7ec8    ; /* 004a7ec8 */
extern int            DAT_004a87d8    ; /* 004a87d8 */
extern int            DAT_004a87e0    ; /* 004a87e0 */
extern int            DAT_004a87e8    ; /* 004a87e8 */
extern int            DAT_004aaba0    ; /* 004aaba0 */
extern int            DAT_004aad78    ; /* 004aad78 */
extern int            DAT_004aaed8    ; /* 004aaed8 */
extern int            DAT_004ab250    ; /* 004ab250 */
extern int            DAT_004ab2d4    ; /* 004ab2d4 */
extern int            DAT_004ab4f0    ; /* 004ab4f0 */
extern int            DAT_004ab554    ; /* 004ab554 */
extern int            DAT_004ab5d0    ; /* 004ab5d0 */
extern int            DAT_004ad134    ; /* 004ad134 */
extern uint           DAT_004ad138    ; /* 004ad138 */
extern int            DAT_004ad13c    ; /* 004ad13c */
extern int            DAT_004ad140    ; /* 004ad140 */
extern int            DAT_004ad144    ; /* 004ad144 */
extern int            DAT_004ad2a8    ; /* 004ad2a8 */
extern int            DAT_004ad2ac    ; /* 004ad2ac */
extern int            DAT_004ad2b0    ; /* 004ad2b0 */
extern int            DAT_004ad2b8    ; /* 004ad2b8 */
extern int            DAT_004ad2bc    ; /* 004ad2bc */
extern int            DAT_004ad3f8    ; /* 004ad3f8 */
extern int            DAT_004ad4b0    ; /* 004ad4b0 */
extern int            DAT_004ad6d0    ; /* 004ad6d0 */
extern int            DAT_004ad7d8    ; /* 004ad7d8 */
extern int            DAT_004ad8dc    ; /* 004ad8dc */
extern int            DAT_004ad8e0    ; /* 004ad8e0 */
extern int            DAT_004ad8e4    ; /* 004ad8e4 */
extern int            DAT_004ad8f0    ; /* 004ad8f0 */
extern int            DAT_004ad9d4    ; /* 004ad9d4 */
extern int            DAT_004ad9d8    ; /* 004ad9d8 */
extern int            DAT_004ad9e0    ; /* 004ad9e0 */
extern int            DAT_004adac8    ; /* 004adac8 */
extern int            DAT_004adacc    ; /* 004adacc */
extern int            DAT_004adae0    ; /* 004adae0 */
extern int            DAT_004adae4    ; /* 004adae4 */
extern int            DAT_004adae8    ; /* 004adae8 */
extern int            DAT_004adaec    ; /* 004adaec */
extern int            DAT_004adaf0    ; /* 004adaf0 */
extern int            DAT_004adaf4    ; /* 004adaf4 */
extern int            DAT_004adaf8    ; /* 004adaf8 */
extern int            DAT_004adafc    ; /* 004adafc */
extern int            DAT_004adb00    ; /* 004adb00 */
extern int            DAT_004adb90    ; /* 004adb90 */
extern int            DAT_004adb94    ; /* 004adb94 */
extern int            DAT_004adb9c    ; /* 004adb9c */
extern int            DAT_004adba0    ; /* 004adba0 */
extern int            DAT_004adbb0    ; /* 004adbb0 */
extern int            DAT_004ade50    ; /* 004ade50 */
extern int            DAT_004adfb0    ; /* 004adfb0 */
extern int            DAT_004adfb4    ; /* 004adfb4 */
extern int            DAT_004adfb8    ; /* 004adfb8 */
extern int            DAT_004adfbc    ; /* 004adfbc */
extern int            DAT_004adfc0    ; /* 004adfc0 */
extern int            DAT_004adfc4    ; /* 004adfc4 */
extern int            DAT_004adfc8    ; /* 004adfc8 */
extern int            DAT_004adfcc    ; /* 004adfcc */
extern int            DAT_004adfd0    ; /* 004adfd0 */
extern int            DAT_004adfd4    ; /* 004adfd4 */
extern int            DAT_004adfd8    ; /* 004adfd8 */
extern int            DAT_004adfdc    ; /* 004adfdc */
extern int            DAT_004ae0e0    ; /* 004ae0e0 */
extern int            DAT_004ae298    ; /* 004ae298 */
extern int            DAT_004ae29c    ; /* 004ae29c */
extern int            DAT_004ae2cc    ; /* 004ae2cc */
extern int            DAT_004ae2d0    ; /* 004ae2d0 */
extern int            DAT_004ae308    ; /* 004ae308 */
extern int            DAT_004ae30c    ; /* 004ae30c */
extern int            DAT_004ae310    ; /* 004ae310 */
extern int            DAT_004ae314    ; /* 004ae314 */
extern int            DAT_004ae320    ; /* 004ae320 */
extern int            DAT_004ae424    ; /* 004ae424 */
extern int            DAT_004ae448    ; /* 004ae448 */
extern int            DAT_004ae531    ; /* 004ae531 */
extern int            DAT_004ae534    ; /* 004ae534 */
extern int            DAT_004ae538    ; /* 004ae538 */
extern int            DAT_004ae590    ; /* 004ae590 */
extern int            DAT_004ae5a0    ; /* 004ae5a0 */
extern int            DAT_004ae5a4    ; /* 004ae5a4 */
extern int            DAT_004ae5aa    ; /* 004ae5aa */
extern int            DAT_004aeb20    ; /* 004aeb20 */
extern int            DAT_004aebd0    ; /* 004aebd0 */
extern int            DAT_004aebd4    ; /* 004aebd4 */
extern int            DAT_004aebf0    ; /* 004aebf0 */
extern int            DAT_004aec30    ; /* 004aec30 */
extern int            DAT_004aedb0    ; /* 004aedb0 */
extern int            DAT_004aedf0    ; /* 004aedf0 */
extern int            DAT_004aee10    ; /* 004aee10 */
extern int            DAT_004aeeb4    ; /* 004aeeb4 */
extern int            DAT_004aeefc    ; /* 004aeefc */
extern int            DAT_004aef14    ; /* 004aef14 */
extern int            DAT_004af0f8    ; /* 004af0f8 */
extern int            DAT_004af0fc    ; /* 004af0fc */
extern int            DAT_004af118    ; /* 004af118 */
extern int            DAT_004af120    ; /* 004af120 */
extern int            DAT_004af160    ; /* 004af160 */
extern int            DAT_004af168    ; /* 004af168 */
extern int            DAT_004af16c    ; /* 004af16c */
extern int            DAT_004af170    ; /* 004af170 */
extern int            DAT_004af174    ; /* 004af174 */
extern int            DAT_004af208    ; /* 004af208 */
extern int            DAT_004af280    ; /* 004af280 */
extern int            DAT_004af344    ; /* 004af344 */
extern int            DAT_004af348    ; /* 004af348 */
extern int            DAT_004af34c    ; /* 004af34c */
extern int            DAT_004af4f0    ; /* 004af4f0 */
extern int            DAT_004b0870    ; /* 004b0870 */
extern int            DAT_004b0bb0    ; /* 004b0bb0 */
extern int            DAT_004b0bd0    ; /* 004b0bd0 */
extern int            DAT_004b0c10    ; /* 004b0c10 */
extern int            DAT_004b0c30    ; /* 004b0c30 */
extern int            DAT_004b0c40    ; /* 004b0c40 */
extern int            DAT_004b0c44    ; /* 004b0c44 */
extern int            DAT_004b0c48    ; /* 004b0c48 */
extern int            DAT_004b0c4c    ; /* 004b0c4c */
extern int            DAT_004b0c50    ; /* 004b0c50 */
extern int            DAT_004b0c54    ; /* 004b0c54 */
extern int            DAT_004b0c58    ; /* 004b0c58 */
extern int            DAT_004b0c5c    ; /* 004b0c5c */
extern int            DAT_004b0c60    ; /* 004b0c60 */
extern int            DAT_004b0c78    ; /* 004b0c78 */
extern int            DAT_004b0c90    ; /* 004b0c90 */
extern int            DAT_004b0c94    ; /* 004b0c94 */
extern int            DAT_004b0c98    ; /* 004b0c98 */
extern int            DAT_004b0c9c    ; /* 004b0c9c */
extern int            DAT_004b0ca0    ; /* 004b0ca0 */
extern int            DAT_004b0ca4    ; /* 004b0ca4 */
extern int            DAT_004b0ca8    ; /* 004b0ca8 */
extern int            DAT_004b0cac    ; /* 004b0cac */
extern int            DAT_004b0cb0    ; /* 004b0cb0 */
extern int            DAT_004b0cb4    ; /* 004b0cb4 */
extern int            DAT_004b0cb8    ; /* 004b0cb8 */
extern int            DAT_004b0cbc    ; /* 004b0cbc */
extern int            DAT_004b0cc0    ; /* 004b0cc0 */
extern int            DAT_004b0cc4    ; /* 004b0cc4 */
extern int            DAT_004b0cc8    ; /* 004b0cc8 */
extern int            DAT_004b0ccc    ; /* 004b0ccc */
extern int            DAT_004b0cd0    ; /* 004b0cd0 */
extern int            DAT_004b0cd4    ; /* 004b0cd4 */
extern int            DAT_004b0cd8    ; /* 004b0cd8 */
extern int            DAT_004b0cdc    ; /* 004b0cdc */
extern int            DAT_004b0ce0    ; /* 004b0ce0 */
extern int            DAT_004b0ce4    ; /* 004b0ce4 */
extern int            DAT_004b0ce8    ; /* 004b0ce8 */
extern int            DAT_004b0cec    ; /* 004b0cec */
extern int            DAT_004b0cf4    ; /* 004b0cf4 */
extern int            DAT_004b0d48    ; /* 004b0d48 */
extern int            DAT_004b0e48    ; /* 004b0e48 */
extern int            DAT_004b0e4c    ; /* 004b0e4c */
extern int            DAT_004b0e50    ; /* 004b0e50 */
extern int            DAT_004b0e54    ; /* 004b0e54 */
extern int            DAT_004b0e58    ; /* 004b0e58 */
extern int            DAT_004b0e5c    ; /* 004b0e5c */
extern int            DAT_004b0e60    ; /* 004b0e60 */
extern int            DAT_004b0e64    ; /* 004b0e64 */
extern undefined4 *   DAT_004b0e68    ; /* 004b0e68 */
extern int            DAT_004b0e88    ; /* 004b0e88 */
extern int            DAT_004b0ec8    ; /* 004b0ec8 */
extern int            DAT_004b2ecc    ; /* 004b2ecc */
extern int            DAT_004b2ed0    ; /* 004b2ed0 */
extern int            DAT_004b2f48    ; /* 004b2f48 */
extern int            DAT_004b2f84    ; /* 004b2f84 */
extern int            DAT_004b2f90    ; /* 004b2f90 */
extern int            DAT_004b2fd4    ; /* 004b2fd4 */
extern int            DAT_004b3070    ; /* 004b3070 */
extern int            DAT_004b31a8    ; /* 004b31a8 */
extern int            DAT_004b31b4    ; /* 004b31b4 */
extern int            DAT_004b31c0    ; /* 004b31c0 */
extern int            DAT_004b31cc    ; /* 004b31cc */
extern int            DAT_004b31d8    ; /* 004b31d8 */
extern int            DAT_004b3358    ; /* 004b3358 */
extern int            DAT_004b33f0    ; /* 004b33f0 */
extern int            DAT_004b3560    ; /* 004b3560 */
extern int            DAT_004b3570    ; /* 004b3570 */
extern int            DAT_004b3580    ; /* 004b3580 */
extern int            DAT_004b3590    ; /* 004b3590 */
extern int            DAT_004b35a0    ; /* 004b35a0 */
extern int            DAT_004b35b0    ; /* 004b35b0 */
extern int            DAT_004b35b8    ; /* 004b35b8 */
extern int            DAT_004b35dc    ; /* 004b35dc */
extern int            DAT_004b360c    ; /* 004b360c */
extern int            DAT_004b37a0    ; /* 004b37a0 */
extern int            DAT_004b37a8    ; /* 004b37a8 */
extern int            DAT_004b38c0    ; /* 004b38c0 */
extern int            DAT_004b38d0    ; /* 004b38d0 */
extern int            DAT_004b38d8    ; /* 004b38d8 */
extern int            DAT_004b3930    ; /* 004b3930 */
extern int            DAT_004b39f0    ; /* 004b39f0 */
extern int            DAT_004b3c04    ; /* 004b3c04 */
extern int            DAT_004b3c08    ; /* 004b3c08 */
extern int            DAT_004b3d58    ; /* 004b3d58 */
extern int            DAT_004b3d5c    ; /* 004b3d5c */
extern int            DAT_004b3d60    ; /* 004b3d60 */
extern int            DAT_004b3d64    ; /* 004b3d64 */
extern int            DAT_004b3d68    ; /* 004b3d68 */
extern int            DAT_004b3d6c    ; /* 004b3d6c */
extern int            DAT_004b3d80    ; /* 004b3d80 */
extern int            DAT_004b3d84    ; /* 004b3d84 */
extern undefined4 *   DAT_004b3d88    ; /* 004b3d88 */
extern int            DAT_004b3d90    ; /* 004b3d90 */
extern int            DAT_004b3d94    ; /* 004b3d94 */
extern int            DAT_004b3d98    ; /* 004b3d98 */
extern int            DAT_004b3da0    ; /* 004b3da0 */
extern int            DAT_004b3da8    ; /* 004b3da8 */
extern int            DAT_004b3dc1    ; /* 004b3dc1 */
extern int            DAT_004b3ec5    ; /* 004b3ec5 */
extern int            DAT_004b40bc    ; /* 004b40bc */
extern int            DAT_004b40c0    ; /* 004b40c0 */
extern int            DAT_004b40c4    ; /* 004b40c4 */
extern int            DAT_004b40dc    ; /* 004b40dc */
extern int            DAT_004b4100    ; /* 004b4100 */
extern int            DAT_004b4104    ; /* 004b4104 */
extern int            DAT_004b4108    ; /* 004b4108 */
extern int            DAT_004b410c    ; /* 004b410c */
extern int            DAT_004b4110    ; /* 004b4110 */
extern int            DAT_004b4114    ; /* 004b4114 */
extern int            DAT_004b4118    ; /* 004b4118 */
extern int            DAT_004b411c    ; /* 004b411c */
extern int            DAT_004b415c    ; /* 004b415c */
extern int            DAT_004b415e    ; /* 004b415e */
extern int            DAT_004b4160    ; /* 004b4160 */
extern int            DAT_004b4162    ; /* 004b4162 */
extern int            DAT_004b4164    ; /* 004b4164 */
extern int            DAT_004b4166    ; /* 004b4166 */
extern int            DAT_004b4168    ; /* 004b4168 */
extern int            DAT_004b416a    ; /* 004b416a */
extern int            DAT_004b416c    ; /* 004b416c */
extern int            DAT_004b4170    ; /* 004b4170 */
extern int            DAT_004b41b0    ; /* 004b41b0 */
extern int            DAT_004b41b2    ; /* 004b41b2 */
extern int            DAT_004b41b4    ; /* 004b41b4 */
extern int            DAT_004b41b6    ; /* 004b41b6 */
extern int            DAT_004b41b8    ; /* 004b41b8 */
extern int            DAT_004b41ba    ; /* 004b41ba */
extern int            DAT_004b41bc    ; /* 004b41bc */
extern int            DAT_004b41be    ; /* 004b41be */
extern int            DAT_004b41c0    ; /* 004b41c0 */
extern int            DAT_004b41c4    ; /* 004b41c4 */
extern int            DAT_004b41c8    ; /* 004b41c8 */
extern int            DAT_004b41cc    ; /* 004b41cc */
extern int            DAT_004b41d0    ; /* 004b41d0 */
extern int            DAT_004b41d4    ; /* 004b41d4 */
extern int            DAT_004b41dc    ; /* 004b41dc */
extern int            DAT_004b41e0    ; /* 004b41e0 */
extern int            DAT_004b42e4    ; /* 004b42e4 */
extern int            DAT_004b42e8    ; /* 004b42e8 */
extern int            DAT_004b42f4    ; /* 004b42f4 */
extern int            DAT_004b42f8    ; /* 004b42f8 */
extern int            DAT_004b430c    ; /* 004b430c */
extern int            DAT_004b4310    ; /* 004b4310 */
extern int            DAT_004b4314    ; /* 004b4314 */
extern undefined4     DAT_004b4318    ; /* 004b4318 */
extern int            DAT_004b431c    ; /* 004b431c */
extern int            DAT_004b4320    ; /* 004b4320 */
extern int            DAT_004b4324    ; /* 004b4324 */
extern int            DAT_004b4328    ; /* 004b4328 */
extern int            DAT_004b432c    ; /* 004b432c */
extern int            DAT_004b4330    ; /* 004b4330 */
extern int            DAT_004b4331    ; /* 004b4331 */
extern int            DAT_004b4334    ; /* 004b4334 */
extern int            DAT_004b4358    ; /* 004b4358 */
extern int            DAT_004b4368    ; /* 004b4368 */
extern int            DAT_004b436c    ; /* 004b436c */
extern int            DAT_004b4370    ; /* 004b4370 */
extern int            DAT_004b4374    ; /* 004b4374 */
extern int            DAT_004b437c    ; /* 004b437c */
extern int            DAT_004b4380    ; /* 004b4380 */
extern int            DAT_004b4384    ; /* 004b4384 */
extern int            DAT_004b4388    ; /* 004b4388 */
extern int            DAT_004b438c    ; /* 004b438c */
extern int            DAT_004b4390    ; /* 004b4390 */
extern int            DAT_004b4394    ; /* 004b4394 */
extern int            DAT_004b4398    ; /* 004b4398 */
extern int            DAT_004b43a0    ; /* 004b43a0 */
extern int            DAT_004b43a4    ; /* 004b43a4 */
extern int            DAT_004b43ac    ; /* 004b43ac */
extern int            DAT_004b43b0    ; /* 004b43b0 */
extern undefined4 *   DAT_004b43b8    ; /* 004b43b8 */
extern undefined4 *   DAT_004b43bc    ; /* 004b43bc */
extern undefined4 *   DAT_004b43c0    ; /* 004b43c0 */
extern undefined4 *   DAT_004b43c4    ; /* 004b43c4 */
extern undefined4 *   DAT_004b43c8    ; /* 004b43c8 */
extern undefined4 *   DAT_004b43cc    ; /* 004b43cc */
extern int            DAT_004b43d0    ; /* 004b43d0 */
extern undefined4 *   DAT_004b43d4    ; /* 004b43d4 */
extern undefined4 *   DAT_004b43d8    ; /* 004b43d8 */
extern undefined4 *   DAT_004b43dc    ; /* 004b43dc */
extern undefined4 *   DAT_004b43e0    ; /* 004b43e0 */
extern undefined4 *   DAT_004b43e4    ; /* 004b43e4 */
extern int            DAT_004b43e8    ; /* 004b43e8 */
extern undefined4 *   DAT_004b44e8    ; /* 004b44e8 */
extern undefined4 *   DAT_004b44f0    ; /* 004b44f0 */
extern undefined4 *   DAT_004b44f4    ; /* 004b44f4 */
extern undefined4 *   DAT_004b44f8    ; /* 004b44f8 */
extern int            DAT_004b44fc    ; /* 004b44fc */
extern int            DAT_004b4500    ; /* 004b4500 */
extern int            DAT_004b4504    ; /* 004b4504 */
extern int            DAT_004b4508    ; /* 004b4508 */
extern int            DAT_004b450c    ; /* 004b450c */
extern undefined4 *   DAT_004b4510    ; /* 004b4510 */
extern undefined4 *   DAT_004b4514    ; /* 004b4514 */
extern undefined4 *   DAT_004b4518    ; /* 004b4518 */
extern undefined4 *   DAT_004b451c    ; /* 004b451c */
extern undefined4 *   DAT_004b4524    ; /* 004b4524 */
extern int            DAT_004b4528    ; /* 004b4528 */
extern int            DAT_004b452c    ; /* 004b452c */
extern undefined4 *   DAT_004b4530    ; /* 004b4530 */
extern undefined4 *   DAT_004b4534    ; /* 004b4534 */
extern int            DAT_004b4538    ; /* 004b4538 */
extern int            DAT_004b453c    ; /* 004b453c */
extern int            DAT_004b4540    ; /* 004b4540 */
extern int            DAT_004b4544    ; /* 004b4544 */
extern int            DAT_004b4548    ; /* 004b4548 */
extern int            DAT_004b454c    ; /* 004b454c */
extern int            DAT_004b4550    ; /* 004b4550 */
extern int            DAT_004b4554    ; /* 004b4554 */
extern int            DAT_004b50bc    ; /* 004b50bc */
extern int            DAT_004b50c0    ; /* 004b50c0 */
extern int            DAT_004b50c4    ; /* 004b50c4 */
extern int            DAT_004b50c8    ; /* 004b50c8 */
extern int            DAT_004b50d4    ; /* 004b50d4 */
extern int            DAT_004b50d8    ; /* 004b50d8 */
extern int            DAT_004b50dc    ; /* 004b50dc */
extern int            DAT_004b50e0    ; /* 004b50e0 */
extern int            DAT_004b5120    ; /* 004b5120 */
extern int            DAT_004b5124    ; /* 004b5124 */
extern int            DAT_004b512c    ; /* 004b512c */
extern int            DAT_004b5130    ; /* 004b5130 */
extern int            DAT_004b5134    ; /* 004b5134 */
extern int            DAT_004b5138    ; /* 004b5138 */
extern int            DAT_004b513c    ; /* 004b513c */
extern int            DAT_004b5140    ; /* 004b5140 */
extern int            DAT_004b55f8    ; /* 004b55f8 */
extern int            DAT_004b5638    ; /* 004b5638 */
extern int            DAT_004b563c    ; /* 004b563c */
extern int            DAT_004b5640    ; /* 004b5640 */
extern int            DAT_004b5641    ; /* 004b5641 */
extern int            DAT_004b5642    ; /* 004b5642 */
extern int            DAT_004b5643    ; /* 004b5643 */
extern int            DAT_004b5644    ; /* 004b5644 */
extern int            DAT_004b5646    ; /* 004b5646 */
extern int            DAT_004b5647    ; /* 004b5647 */
extern int            DAT_004b5648    ; /* 004b5648 */
extern int            DAT_004b564c    ; /* 004b564c */
extern int            DAT_004b5650    ; /* 004b5650 */
extern int            DAT_004b5654    ; /* 004b5654 */
extern int            DAT_004b5658    ; /* 004b5658 */
extern int            DAT_004b565c    ; /* 004b565c */
extern int            DAT_004b5660    ; /* 004b5660 */
extern int            DAT_004b5664    ; /* 004b5664 */
extern int            DAT_004b5668    ; /* 004b5668 */
extern int            DAT_004b566c    ; /* 004b566c */
extern int            DAT_004b5670    ; /* 004b5670 */
extern int            DAT_004b5674    ; /* 004b5674 */
extern int            DAT_004b5678    ; /* 004b5678 */
extern int            DAT_004b567c    ; /* 004b567c */
extern int            DAT_004b5680    ; /* 004b5680 */
extern int            DAT_004b5684    ; /* 004b5684 */
extern int            DAT_004b5688    ; /* 004b5688 */
extern int            DAT_004b568c    ; /* 004b568c */
extern int            DAT_004b5690    ; /* 004b5690 */
extern int            DAT_004b5694    ; /* 004b5694 */
extern int            DAT_004b5698    ; /* 004b5698 */
extern int            DAT_004b569c    ; /* 004b569c */
extern int            DAT_004b56a0    ; /* 004b56a0 */
extern int            DAT_004b56a4    ; /* 004b56a4 */
extern int            DAT_004cc548    ; /* 004cc548 */
extern int            DAT_004cc54c    ; /* 004cc54c */
extern int            DAT_004cc550    ; /* 004cc550 */
extern int            DAT_004cc551    ; /* 004cc551 */
extern int            DAT_004ce550    ; /* 004ce550 */
extern int            DAT_004ce554    ; /* 004ce554 */
extern int            DAT_004ce55c    ; /* 004ce55c */
extern int            DAT_004ce568    ; /* 004ce568 */
extern int            DAT_004ce570    ; /* 004ce570 */
extern int            DAT_004ce898    ; /* 004ce898 */
extern undefined4 *   DAT_004ce89c    ; /* 004ce89c */
extern int            DAT_004ce8a0    ; /* 004ce8a0 */
extern int            DAT_004ce8a4    ; /* 004ce8a4 */
extern int            DAT_004ce8a8    ; /* 004ce8a8 */
extern int            DAT_004ce8ac    ; /* 004ce8ac */
extern int            DAT_004ce8b0    ; /* 004ce8b0 */
extern int            DAT_004ce8b4    ; /* 004ce8b4 */
extern int            DAT_004ce8b8    ; /* 004ce8b8 */
extern int            DAT_004ce8bc    ; /* 004ce8bc */
extern int            DAT_004ce8c0    ; /* 004ce8c0 */
extern int            DAT_004ce8c8    ; /* 004ce8c8 */
extern undefined4 *   DAT_004ce8cc    ; /* 004ce8cc */
extern int            DAT_004ce8d0    ; /* 004ce8d0 */
extern int            DAT_004ce8d4    ; /* 004ce8d4 */
extern int            DAT_004ce8d8    ; /* 004ce8d8 */
extern int            DAT_004ce8dc    ; /* 004ce8dc */
extern int            DAT_004ce8e0    ; /* 004ce8e0 */
extern int            DAT_004ce8e8    ; /* 004ce8e8 */
extern undefined4 *   DAT_004ce8ec    ; /* 004ce8ec */
extern undefined4 *   DAT_004ce8f0    ; /* 004ce8f0 */
extern int            DAT_004ce8f8    ; /* 004ce8f8 */
extern undefined4 *   DAT_004ce8fc    ; /* 004ce8fc */
extern undefined4 *   DAT_004ce908    ; /* 004ce908 */
extern undefined4 *   DAT_004ce90c    ; /* 004ce90c */
extern int            DAT_004ce914    ; /* 004ce914 */
extern int            DAT_004ce940    ; /* 004ce940 */
extern int            DAT_004ce944    ; /* 004ce944 */
extern int            DAT_004ce984    ; /* 004ce984 */
extern int            DAT_004ce9c4    ; /* 004ce9c4 */
extern int            DAT_004ce9dc    ; /* 004ce9dc */
extern int            DAT_004ce9e0    ; /* 004ce9e0 */
extern int            DAT_004ce9e4    ; /* 004ce9e4 */
extern int            DAT_004ce9fc    ; /* 004ce9fc */
extern int            DAT_004cea10    ; /* 004cea10 */
extern int            DAT_004cea14    ; /* 004cea14 */
extern int            DAT_004cea8c    ; /* 004cea8c */
extern int            DAT_004cea90    ; /* 004cea90 */
extern undefined4 *   DAT_004cea94    ; /* 004cea94 */
extern undefined4 *   DAT_004cea98    ; /* 004cea98 */
extern undefined4 *   DAT_004cea9c    ; /* 004cea9c */
extern undefined4 *   DAT_004ceaa4    ; /* 004ceaa4 */
extern undefined4 *   DAT_004ceaa8    ; /* 004ceaa8 */
extern undefined4 *   DAT_004ceaac    ; /* 004ceaac */
extern int            DAT_004ceab0    ; /* 004ceab0 */
extern int            DAT_004ceab4    ; /* 004ceab4 */
extern int            DAT_004ceab8    ; /* 004ceab8 */
extern int            DAT_004ceabc    ; /* 004ceabc */
extern int            DAT_004ceac0    ; /* 004ceac0 */
extern int            DAT_004ceac4    ; /* 004ceac4 */
extern char           DAT_004ceaca    ; /* 004ceaca */
extern int            DAT_004ceacb    ; /* 004ceacb */
extern int            DAT_004ceacc    ; /* 004ceacc */
extern int            DAT_004ceacd    ; /* 004ceacd */
extern int            DAT_004ceace    ; /* 004ceace */
extern int            DAT_004ceacf    ; /* 004ceacf */
extern char           DAT_004cead0    ; /* 004cead0 */
extern char           DAT_004cead1    ; /* 004cead1 */
extern int            DAT_004cead2    ; /* 004cead2 */
extern int            DAT_004cead3    ; /* 004cead3 */
extern int            DAT_004cead8    ; /* 004cead8 */
extern int            DAT_004ceadc    ; /* 004ceadc */
extern int            DAT_004ceae8    ; /* 004ceae8 */
extern int            DAT_004ceaec    ; /* 004ceaec */
extern int            DAT_004ceb38    ; /* 004ceb38 */
extern int            DAT_004ceb78    ; /* 004ceb78 */
extern int            DAT_004cebb8    ; /* 004cebb8 */
extern int            DAT_004cec04    ; /* 004cec04 */
extern int            DAT_004ced1c    ; /* 004ced1c */
extern int            DAT_004cede8    ; /* 004cede8 */
extern int            DAT_004cedec    ; /* 004cedec */
extern int            DAT_004cedf0    ; /* 004cedf0 */
extern int            DAT_004cedf4    ; /* 004cedf4 */
extern int            DAT_004cee34    ; /* 004cee34 */
extern int            DAT_004cee40    ; /* 004cee40 */
extern int            DAT_004cee4c    ; /* 004cee4c */
extern int            DAT_004cee64    ; /* 004cee64 */
extern int            DAT_004cee70    ; /* 004cee70 */
extern int            DAT_004cee78    ; /* 004cee78 */
extern int            DAT_004cee84    ; /* 004cee84 */
extern int            DAT_004ceedc    ; /* 004ceedc */
extern int            DAT_004cef14    ; /* 004cef14 */
extern int            DAT_004cefb8    ; /* 004cefb8 */
extern int            DAT_004cefcc    ; /* 004cefcc */
extern undefined4 *   DAT_004cefd0    ; /* 004cefd0 */
extern int            DAT_004cefd4    ; /* 004cefd4 */
extern int            DAT_004cf0e0    ; /* 004cf0e0 */
extern int            DAT_004cf0f8    ; /* 004cf0f8 */
extern int            DAT_004cf128    ; /* 004cf128 */
extern int            DAT_004cf140    ; /* 004cf140 */
extern int            DAT_004cf170    ; /* 004cf170 */
extern int            DAT_004cf188    ; /* 004cf188 */
extern int            DAT_004cf1d0    ; /* 004cf1d0 */
extern int            DAT_004cf1e8    ; /* 004cf1e8 */
extern int            DAT_004cf200    ; /* 004cf200 */
extern char           DAT_004cf218    ; /* 004cf218 */
extern char           DAT_004cf21a    ; /* 004cf21a */
extern char           DAT_004cf21b    ; /* 004cf21b */
extern char           DAT_004cf21d    ; /* 004cf21d */
extern char           DAT_004cf21e    ; /* 004cf21e */
extern char           DAT_004cf221    ; /* 004cf221 */
extern char           DAT_004cf222    ; /* 004cf222 */
extern char           DAT_004cf223    ; /* 004cf223 */
extern int            DAT_004cf278    ; /* 004cf278 */
extern undefined4 *   DAT_004cf28c    ; /* 004cf28c */
extern int            DAT_004cf2a8    ; /* 004cf2a8 */
extern int            DAT_004cf2b0    ; /* 004cf2b0 */
extern int            DAT_004cf3f0    ; /* 004cf3f0 */
extern int            DAT_004cf3f4    ; /* 004cf3f4 */
extern int            DAT_004cf3f8    ; /* 004cf3f8 */
extern int            DAT_004cf3fc    ; /* 004cf3fc */
extern int            DAT_004cf400    ; /* 004cf400 */
extern int            DAT_004cf404    ; /* 004cf404 */
extern int            DAT_004cf408    ; /* 004cf408 */
extern int            DAT_004cf410    ; /* 004cf410 */
extern int            DAT_004cf418    ; /* 004cf418 */
extern int            DAT_004cf41c    ; /* 004cf41c */
extern int            DAT_004cf420    ; /* 004cf420 */
extern int            DAT_004cf424    ; /* 004cf424 */
extern int            DAT_004cf428    ; /* 004cf428 */
extern int            DAT_004cf42c    ; /* 004cf42c */
extern int            DAT_004cf468    ; /* 004cf468 */
extern undefined4 *   DAT_004cf4e8    ; /* 004cf4e8 */
extern undefined4 *   DAT_004cf4f0    ; /* 004cf4f0 */
extern int            DAT_004cf4f4    ; /* 004cf4f4 */
extern int            DAT_004cf4f8    ; /* 004cf4f8 */
extern int            DAT_004cf4fc    ; /* 004cf4fc */
extern int            DAT_004cf500    ; /* 004cf500 */
extern int            DAT_004cf508    ; /* 004cf508 */
extern int            DAT_004cf538    ; /* 004cf538 */
extern int            DAT_004cf568    ; /* 004cf568 */
extern int            DAT_004d0d68    ; /* 004d0d68 */
extern int            DAT_004d0da8    ; /* 004d0da8 */
extern int            DAT_004d0de8    ; /* 004d0de8 */
extern int            DAT_004d0e28    ; /* 004d0e28 */
extern undefined4 *   DAT_004d0e6c    ; /* 004d0e6c */
extern int            DAT_004d0e70    ; /* 004d0e70 */
extern int            DAT_004d0e74    ; /* 004d0e74 */
extern int            DAT_004d0e78    ; /* 004d0e78 */
extern int            DAT_004d0e84    ; /* 004d0e84 */
extern int            DAT_004d1068    ; /* 004d1068 */
extern int            DAT_004d1380    ; /* 004d1380 */
extern int            DAT_004d1410    ; /* 004d1410 */
extern int            DAT_004d14d4    ; /* 004d14d4 */
extern int            DAT_004d3654    ; /* 004d3654 */
extern int            DAT_004d4654    ; /* 004d4654 */
extern undefined4 *   DAT_004d4754    ; /* 004d4754 */
extern int            DAT_004d4758    ; /* 004d4758 */
extern int            DAT_004d4760    ; /* 004d4760 */
extern int            DAT_004d4764    ; /* 004d4764 */
extern int            DAT_004d4768    ; /* 004d4768 */
extern int            DAT_004d476c    ; /* 004d476c */
extern int            DAT_004d4770    ; /* 004d4770 */
extern int            DAT_004d4774    ; /* 004d4774 */
extern int            DAT_004d477c    ; /* 004d477c */
extern int            DAT_004d4780    ; /* 004d4780 */
extern int            DAT_004d47e8    ; /* 004d47e8 */
extern int            DAT_004d47ec    ; /* 004d47ec */
extern int            DAT_004d47f0    ; /* 004d47f0 */
extern int            DAT_004d47f8    ; /* 004d47f8 */
extern int            DAT_004d4804    ; /* 004d4804 */
extern int            DAT_004d4808    ; /* 004d4808 */
extern int            DAT_004d480c    ; /* 004d480c */
extern int            DAT_004d4820    ; /* 004d4820 */
extern int            DAT_004d4824    ; /* 004d4824 */
extern int            DAT_004d4828    ; /* 004d4828 */
extern int            DAT_004d483c    ; /* 004d483c */
extern int            DAT_004d4840    ; /* 004d4840 */
extern int            DAT_004d4844    ; /* 004d4844 */
extern int            DAT_004d48b8    ; /* 004d48b8 */
extern int            DAT_004d48c0    ; /* 004d48c0 */
extern int            DAT_004d48c4    ; /* 004d48c4 */
extern int            DAT_004d494c    ; /* 004d494c */
extern int            DAT_004d4958    ; /* 004d4958 */
extern int            DAT_004d49cc    ; /* 004d49cc */
extern int            DAT_004d49d0    ; /* 004d49d0 */
extern int            DAT_004d49dc    ; /* 004d49dc */
extern int            DAT_004d49e0    ; /* 004d49e0 */
extern int            DAT_004d49f0    ; /* 004d49f0 */
extern int            DAT_004d49f4    ; /* 004d49f4 */
extern int            DAT_004d49f8    ; /* 004d49f8 */
extern int            DAT_004d49fc    ; /* 004d49fc */
extern undefined4 *   DAT_004d4c90    ; /* 004d4c90 */
extern int            DAT_004d4c94    ; /* 004d4c94 */
extern int            DAT_004d4ca2    ; /* 004d4ca2 */
extern int            DAT_004d4ca3    ; /* 004d4ca3 */
extern int            DAT_004d4ca4    ; /* 004d4ca4 */
extern int            DAT_004d4ca5    ; /* 004d4ca5 */
extern int            DAT_004d4ca6    ; /* 004d4ca6 */
extern int            DAT_004d4ca7    ; /* 004d4ca7 */
extern int            DAT_004d4ca8    ; /* 004d4ca8 */
extern int            DAT_004d4ca9    ; /* 004d4ca9 */
extern int            DAT_004d4caa    ; /* 004d4caa */
extern int            DAT_004d4cd1    ; /* 004d4cd1 */
extern int            DAT_004d4cd2    ; /* 004d4cd2 */
extern int            DAT_004d4cd3    ; /* 004d4cd3 */
extern int            DAT_004d4cd4    ; /* 004d4cd4 */
extern int            DAT_004d4cd5    ; /* 004d4cd5 */
extern int            DAT_004d4cd6    ; /* 004d4cd6 */
extern int            DAT_004d4cd7    ; /* 004d4cd7 */
extern int            DAT_004d4cd8    ; /* 004d4cd8 */
extern int            DAT_004d4cd9    ; /* 004d4cd9 */
extern int            DAT_004d4da0    ; /* 004d4da0 */
extern int            DAT_004d4da1    ; /* 004d4da1 */
extern int            DAT_004d4da2    ; /* 004d4da2 */
extern int            DAT_004d4da3    ; /* 004d4da3 */
extern int            DAT_004d4db0    ; /* 004d4db0 */
extern int            DAT_004d4db1    ; /* 004d4db1 */
extern int            DAT_004d4db2    ; /* 004d4db2 */
extern int            DAT_004d4db3    ; /* 004d4db3 */
extern int            DAT_004d4db4    ; /* 004d4db4 */
extern int            DAT_004d4db5    ; /* 004d4db5 */
extern int            DAT_004d4db6    ; /* 004d4db6 */
extern int            DAT_004d4db7    ; /* 004d4db7 */
extern int            DAT_004d4db8    ; /* 004d4db8 */
extern int            DAT_004d4db9    ; /* 004d4db9 */
extern int            DAT_004d4dbe    ; /* 004d4dbe */
extern int            DAT_004d4dbf    ; /* 004d4dbf */
extern int            DAT_004d4dc0    ; /* 004d4dc0 */
extern int            DAT_004d4dc1    ; /* 004d4dc1 */
extern int            DAT_004d4dc2    ; /* 004d4dc2 */
extern int            DAT_004d4dc3    ; /* 004d4dc3 */
extern int            DAT_004d4dc4    ; /* 004d4dc4 */
extern int            DAT_004d4dc5    ; /* 004d4dc5 */
extern int            DAT_004d4dc6    ; /* 004d4dc6 */
extern int            DAT_004d4dcc    ; /* 004d4dcc */
extern int            DAT_004d4dcd    ; /* 004d4dcd */
extern int            DAT_004d4dce    ; /* 004d4dce */
extern int            DAT_004d4dcf    ; /* 004d4dcf */
extern int            DAT_004d4dd0    ; /* 004d4dd0 */
extern int            DAT_004d4dd1    ; /* 004d4dd1 */
extern int            DAT_004d4dd2    ; /* 004d4dd2 */
extern int            DAT_004d4ea0    ; /* 004d4ea0 */
extern int            DAT_004d4ea4    ; /* 004d4ea4 */
extern int            DAT_004d4ea8    ; /* 004d4ea8 */
extern int            DAT_004d4eb0    ; /* 004d4eb0 */
extern int            DAT_004d4f34    ; /* 004d4f34 */
extern int            DAT_004d4f38    ; /* 004d4f38 */
extern int            DAT_004d5040    ; /* 004d5040 */
extern int            DAT_004d50c0    ; /* 004d50c0 */
extern int            DAT_004d50d0    ; /* 004d50d0 */
extern int            DAT_004d51d0    ; /* 004d51d0 */
extern int            DAT_004d5211    ; /* 004d5211 */
extern int            DAT_004d5212    ; /* 004d5212 */
extern int            DAT_004d5213    ; /* 004d5213 */
extern int            DAT_004d5214    ; /* 004d5214 */
extern int            DAT_004d5215    ; /* 004d5215 */
extern int            DAT_004d5216    ; /* 004d5216 */
extern int            DAT_004d5217    ; /* 004d5217 */
extern int            DAT_004d5218    ; /* 004d5218 */
extern int            DAT_004d5219    ; /* 004d5219 */
extern int            DAT_004d521a    ; /* 004d521a */
extern int            DAT_004d521b    ; /* 004d521b */
extern int            DAT_004d521c    ; /* 004d521c */
extern int            DAT_004d521d    ; /* 004d521d */
extern int            DAT_004d521e    ; /* 004d521e */
extern int            DAT_004d521f    ; /* 004d521f */
extern int            DAT_004d5220    ; /* 004d5220 */
extern int            DAT_004d5221    ; /* 004d5221 */
extern int            DAT_004d5222    ; /* 004d5222 */
extern int            DAT_004d5223    ; /* 004d5223 */
extern int            DAT_004d5224    ; /* 004d5224 */
extern int            DAT_004d5225    ; /* 004d5225 */
extern int            DAT_004d5226    ; /* 004d5226 */
extern int            DAT_004d5227    ; /* 004d5227 */
extern int            DAT_004d5228    ; /* 004d5228 */
extern int            DAT_004d5229    ; /* 004d5229 */
extern int            DAT_004d522a    ; /* 004d522a */
extern int            DAT_004d52d0    ; /* 004d52d0 */
extern int            DAT_004d52d4    ; /* 004d52d4 */
extern int            DAT_004d52d8    ; /* 004d52d8 */
extern int            DAT_004d52dc    ; /* 004d52dc */
extern int            DAT_004d52e0    ; /* 004d52e0 */
extern int            DAT_004d6300    ; /* 004d6300 */
extern int            DAT_004d6308    ; /* 004d6308 */
extern int            DAT_004d6320    ; /* 004d6320 */
extern int            DAT_004d6428    ; /* 004d6428 */
extern int            DAT_004d642c    ; /* 004d642c */
extern int            DAT_004d6430    ; /* 004d6430 */
extern int            DAT_004d6434    ; /* 004d6434 */
extern int            DAT_004d6438    ; /* 004d6438 */
extern int            DAT_004d6440    ; /* 004d6440 */
extern undefined4 *   DAT_004d6444    ; /* 004d6444 */
extern int            DAT_004d6448    ; /* 004d6448 */
extern int            DAT_004d644c    ; /* 004d644c */
extern int            DAT_004d6450    ; /* 004d6450 */
extern int            DAT_004d6454    ; /* 004d6454 */
extern int            DAT_004d6458    ; /* 004d6458 */
extern int            DAT_004d645c    ; /* 004d645c */
extern int            DAT_004de716    ; /* 004de716 */
extern int            DAT_004debdc    ; /* 004debdc */
extern int            IMAGE_DOS_HEADER_00400000; /* 00400000 */
extern int            PTR_DAT_004723f4; /* 004723f4 */
extern int            PTR_DAT_0049cd68; /* 0049cd68 */
extern int            PTR_DAT_0049dc80; /* 0049dc80 */
extern int            PTR_DAT_004ad8d8; /* 004ad8d8 */
extern int            PTR_DAT_004ad9d0; /* 004ad9d0 */
extern int            PTR_DAT_004adaa8; /* 004adaa8 */
extern int            PTR_DAT_004adab8; /* 004adab8 */
extern int            PTR_DAT_004adac0; /* 004adac0 */
extern int            PTR_DAT_004adb88; /* 004adb88 */
extern int            PTR_DAT_004adbf0; /* 004adbf0 */
extern int            PTR_DAT_004adea4; /* 004adea4 */
extern int            PTR_DAT_004adea8; /* 004adea8 */
extern int            PTR_DAT_004adf68; /* 004adf68 */
extern int            PTR_DAT_004adf6c; /* 004adf6c */
extern int            PTR_DAT_004adf70; /* 004adf70 */
extern int            PTR_DAT_004adf74; /* 004adf74 */
extern int            PTR_DAT_004adf78; /* 004adf78 */
extern int            PTR_DAT_004adf7c; /* 004adf7c */
extern int            PTR_DAT_004adf80; /* 004adf80 */
extern int            PTR_DAT_004adf84; /* 004adf84 */
extern int            PTR_DAT_004adf88; /* 004adf88 */
extern int            PTR_DAT_004adf8c; /* 004adf8c */
extern int            PTR_DAT_004b2ec8; /* 004b2ec8 */
extern int            PTR_DAT_004b33c0; /* 004b33c0 */
extern int            PTR_DAT_004b37ac; /* 004b37ac */
extern int            PTR_FUN_0049cd00; /* 0049cd00 */
extern int            PTR_FUN_0049cd28; /* 0049cd28 */
extern int            PTR_FUN_0049cd48; /* 0049cd48 */
extern int            PTR_FUN_0049cd54; /* 0049cd54 */
extern int            PTR_FUN_0049cd60; /* 0049cd60 */
extern int            PTR_FUN_0049d578; /* 0049d578 */
extern int            PTR_FUN_0049d57c; /* 0049d57c */
extern int            PTR_FUN_0049f384; /* 0049f384 */
extern int            PTR_FUN_0049f390; /* 0049f390 */
extern int            PTR_FUN_0049f39c; /* 0049f39c */
extern int            PTR_FUN_0049f3a8; /* 0049f3a8 */
extern int            PTR_FUN_0049f3f8; /* 0049f3f8 */
extern int            PTR_FUN_0049fc28; /* 0049fc28 */
extern int            PTR_FUN_0049fc6c; /* 0049fc6c */
extern int            PTR_FUN_004a0654; /* 004a0654 */
extern int            PTR_FUN_004a06ac; /* 004a06ac */
extern int            PTR_FUN_004a22dc; /* 004a22dc */
extern int            PTR_FUN_004a241c; /* 004a241c */
extern int            PTR_FUN_004a3738; /* 004a3738 */
extern int            PTR_FUN_004a3b1c; /* 004a3b1c */
extern int            PTR_FUN_004a3b24; /* 004a3b24 */
extern int            PTR_LAB_00421334; /* 00421334 */
extern int            PTR_LAB_0046523c; /* 0046523c */
extern int            PTR_LAB_0049d51c; /* 0049d51c */
extern int            PTR_LAB_0049ddbc; /* 0049ddbc */
extern int            PTR_LAB_0049ddc8; /* 0049ddc8 */
extern int            PTR_LAB_0049ddd4; /* 0049ddd4 */
extern int            PTR_LAB_0049dde0; /* 0049dde0 */
extern int            PTR_LAB_0049ddec; /* 0049ddec */
extern int            PTR_LAB_0049f4b8; /* 0049f4b8 */
extern int            PTR_LAB_0049fc34; /* 0049fc34 */
extern int            PTR_LAB_0049fc50; /* 0049fc50 */
extern int            PTR_LAB_004a05fc; /* 004a05fc */
extern int            PTR_LAB_004a0704; /* 004a0704 */
extern int            PTR_LAB_004a20cc; /* 004a20cc */
extern int            PTR_LAB_004a2304; /* 004a2304 */
extern int            PTR_LAB_004a23d4; /* 004a23d4 */
extern int            PTR_LAB_004ade70; /* 004ade70 */
extern int            PTR_LAB_004ade74; /* 004ade74 */
extern int            PTR_LAB_004ade78; /* 004ade78 */
extern int            PTR_LAB_004ade7c; /* 004ade7c */
extern int            PTR_LAB_004ade80; /* 004ade80 */
extern int            PTR_LAB_004ade84; /* 004ade84 */
extern int            PTR_LAB_004ade88; /* 004ade88 */
extern int            PTR_LAB_004ade8c; /* 004ade8c */
extern int            PTR_LAB_004ade90; /* 004ade90 */
extern int            PTR_LAB_004ade94; /* 004ade94 */
extern int            PTR_LAB_004af164; /* 004af164 */
extern int            PTR_PTR_FUN_004b0cf8; /* 004b0cf8 */
extern int            PTR_PTR_FUN_004b0e6c; /* 004b0e6c */
extern int            PTR_PTR__scalar_deleting_destructor__004ae4d8; /* 004ae4d8 */
extern int            PTR____DestructExceptionObject_0049f3f0; /* 0049f3f0 */
extern int            PTR___exit_004ad3f0; /* 004ad3f0 */
extern int            PTR___fpmath_0049d574; /* 0049d574 */
extern int            PTR__scalar_deleting_destructor__0049cd0c; /* 0049cd0c */
extern int            PTR_caseD_1ba_00419790; /* 00419790 */
extern int            PTR_s_Easy_004aee38; /* 004aee38 */
extern int            PTR_s_LC_COLLATE_0049d43c; /* 0049d43c */
extern int            PTR_s_No___2d__s___2d___2d___2d___2d___004b33b0; /* 004b33b0 */
extern int            PTR_s_R6002___floating_point_support_n_004ad3fc; /* 004ad3fc */
extern int            PTR_s_Type_Descriptor__0049dc5c; /* 0049dc5c */
extern int            PTR_s_UFO_Red_004b33e0; /* 004b33e0 */
extern int            PTR_s___based__0049dc30; /* 0049dc30 */
extern int            PTR_s___pascal_0049dc38; /* 0049dc38 */
extern int            PTR_s__null__004ad3d8; /* 004ad3d8 */
extern int            PTR_s__s__s___2d___2d___2d___2d___2d___004b33b8; /* 004b33b8 */
extern int            PTR_s_bad_allocation_004ad0b0; /* 004ad0b0 */
extern int            PTR_s_demo_demo2_rpy_004b33a4; /* 004b33a4 */
extern int            PTR_s_e00_msg_004af128; /* 004af128 */
extern int            PTR_s_se_plst00_wav_004aea50; /* 004aea50 */
extern int            PTR_u__null__004ad3dc; /* 004ad3dc */
extern int            UNK_004a114c    ; /* 004a114c */
extern int            UNK_004a5f88    ; /* 004a5f88 */
extern int            UNK_004a5fa8    ; /* 004a5fa8 */
extern int            UNK_004a5fb8    ; /* 004a5fb8 */
extern int            UNK_004a5fd8    ; /* 004a5fd8 */
extern int            UNK_004a5fe8    ; /* 004a5fe8 */
extern int            _DAT_004a44a0   ; /* 004a44a0 */
extern int            _DAT_004a5dda   ; /* 004a5dda */
extern int            _DAT_004af5b4   ; /* 004af5b4 */
extern int            _DAT_004b0934   ; /* 004b0934 */
extern int            _DAT_004b0c7c   ; /* 004b0c7c */
extern int            _DAT_004b0c80   ; /* 004b0c80 */
extern int            _DAT_004b0c84   ; /* 004b0c84 */
extern int            _DAT_004b0c88   ; /* 004b0c88 */
extern int            _DAT_004b0c8c   ; /* 004b0c8c */
extern int            _DAT_004b0c98   ; /* 004b0c98 */
extern int            _DAT_004b0c9c   ; /* 004b0c9c */
extern int            _DAT_004b0ca0   ; /* 004b0ca0 */
extern int            _DAT_004b0ca4   ; /* 004b0ca4 */
extern int            _DAT_004b0cf0   ; /* 004b0cf0 */
extern int            _DAT_004b0d18   ; /* 004b0d18 */
extern int            _DAT_004b0d1c   ; /* 004b0d1c */
extern int            _DAT_004b0d24   ; /* 004b0d24 */
extern int            _DAT_004b0d2c   ; /* 004b0d2c */
extern int            _DAT_004b0d44   ; /* 004b0d44 */
extern int            _DAT_004b336c   ; /* 004b336c */
extern int            _DAT_004b35ca   ; /* 004b35ca */
extern int            _DAT_004b3624   ; /* 004b3624 */
extern int            _DAT_004b363c   ; /* 004b363c */
extern int            _DAT_004b3890   ; /* 004b3890 */
extern int            _DAT_004b38a0   ; /* 004b38a0 */
extern int            _DAT_004b38cc   ; /* 004b38cc */
extern int            _DAT_004b38e0   ; /* 004b38e0 */
extern int            _DAT_004b38e4   ; /* 004b38e4 */
extern int            _DAT_004b38ec   ; /* 004b38ec */
extern int            _DAT_004b3938   ; /* 004b3938 */
extern int            _DAT_004b39c4   ; /* 004b39c4 */
extern int            _DAT_004b39c8   ; /* 004b39c8 */
extern int            _DAT_004b39cc   ; /* 004b39cc */
extern int            _DAT_004b39d0   ; /* 004b39d0 */
extern int            _DAT_004b39d4   ; /* 004b39d4 */
extern int            _DAT_004b39d8   ; /* 004b39d8 */
extern int            _DAT_004b39dc   ; /* 004b39dc */
extern int            _DAT_004b39e0   ; /* 004b39e0 */
extern int            _DAT_004b39e4   ; /* 004b39e4 */
extern int            _DAT_004b39e8   ; /* 004b39e8 */
extern int            _DAT_004b39ec   ; /* 004b39ec */
extern int            _DAT_004b39f4   ; /* 004b39f4 */
extern int            _DAT_004b39f8   ; /* 004b39f8 */
extern int            _DAT_004b39fc   ; /* 004b39fc */
extern int            _DAT_004b3a00   ; /* 004b3a00 */
extern int            _DAT_004b3d74   ; /* 004b3d74 */
extern int            _DAT_004b3d78   ; /* 004b3d78 */
extern int            _DAT_004b3d9c   ; /* 004b3d9c */
extern int            _DAT_004b40d0   ; /* 004b40d0 */
extern int            _DAT_004b40d4   ; /* 004b40d4 */
extern int            _DAT_004b40d8   ; /* 004b40d8 */
extern int            _DAT_004b42ec   ; /* 004b42ec */
extern int            _DAT_004b42f0   ; /* 004b42f0 */
extern int            _DAT_004b42fc   ; /* 004b42fc */
extern int            _DAT_004b4300   ; /* 004b4300 */
extern int            _DAT_004b4304   ; /* 004b4304 */
extern int            _DAT_004b4308   ; /* 004b4308 */
extern int            _DAT_004b4334   ; /* 004b4334 */
extern int            _DAT_004b4338   ; /* 004b4338 */
extern int            _DAT_004b433c   ; /* 004b433c */
extern int            _DAT_004b4340   ; /* 004b4340 */
extern int            _DAT_004b4344   ; /* 004b4344 */
extern int            _DAT_004b4348   ; /* 004b4348 */
extern int            _DAT_004b434c   ; /* 004b434c */
extern int            _DAT_004b4350   ; /* 004b4350 */
extern int            _DAT_004b4354   ; /* 004b4354 */
extern int            _DAT_004b4358   ; /* 004b4358 */
extern int            _DAT_004b435c   ; /* 004b435c */
extern int            _DAT_004b4360   ; /* 004b4360 */
extern int            _DAT_004b4364   ; /* 004b4364 */
extern int            _DAT_004b4520   ; /* 004b4520 */
extern int            _DAT_004ce56c   ; /* 004ce56c */
extern int            _DAT_004ce8e8   ; /* 004ce8e8 */
extern int            _DAT_004ce914   ; /* 004ce914 */
extern int            _DAT_004ce9c4   ; /* 004ce9c4 */
extern int            _DAT_004ce9c8   ; /* 004ce9c8 */
extern int            _DAT_004ce9cc   ; /* 004ce9cc */
extern int            _DAT_004ce9d0   ; /* 004ce9d0 */
extern int            _DAT_004ce9d4   ; /* 004ce9d4 */
extern int            _DAT_004ce9d8   ; /* 004ce9d8 */
extern int            _DAT_004cea0c   ; /* 004cea0c */
extern int            _DAT_004cea84   ; /* 004cea84 */
extern int            _DAT_004cea88   ; /* 004cea88 */
extern int            _DAT_004ceae8   ; /* 004ceae8 */
extern int            _DAT_004ceaec   ; /* 004ceaec */
extern int            _DAT_004ceaf0   ; /* 004ceaf0 */
extern int            _DAT_004ceaf4   ; /* 004ceaf4 */
extern int            _DAT_004ceaf8   ; /* 004ceaf8 */
extern int            _DAT_004ceafc   ; /* 004ceafc */
extern int            _DAT_004ceb00   ; /* 004ceb00 */
extern int            _DAT_004ceb04   ; /* 004ceb04 */
extern int            _DAT_004ceb08   ; /* 004ceb08 */
extern int            _DAT_004ceb0c   ; /* 004ceb0c */
extern int            _DAT_004ceb28   ; /* 004ceb28 */
extern int            _DAT_004ceb2c   ; /* 004ceb2c */
extern int            _DAT_004ceb30   ; /* 004ceb30 */
extern int            _DAT_004ceb34   ; /* 004ceb34 */
extern int            _DAT_004cebb8   ; /* 004cebb8 */
extern int            _DAT_004cebbc   ; /* 004cebbc */
extern int            _DAT_004cebc0   ; /* 004cebc0 */
extern int            _DAT_004cebc4   ; /* 004cebc4 */
extern int            _DAT_004cebc8   ; /* 004cebc8 */
extern int            _DAT_004cebcc   ; /* 004cebcc */
extern int            _DAT_004cebd0   ; /* 004cebd0 */
extern int            _DAT_004cebdc   ; /* 004cebdc */
extern int            _DAT_004cebe0   ; /* 004cebe0 */
extern int            _DAT_004cebe4   ; /* 004cebe4 */
extern int            _DAT_004cebe8   ; /* 004cebe8 */
extern int            _DAT_004cebf0   ; /* 004cebf0 */
extern int            _DAT_004cebf4   ; /* 004cebf4 */
extern int            _DAT_004cebf8   ; /* 004cebf8 */
extern int            _DAT_004cec04   ; /* 004cec04 */
extern int            _DAT_004cec08   ; /* 004cec08 */
extern int            _DAT_004cec0c   ; /* 004cec0c */
extern int            _DAT_004cec10   ; /* 004cec10 */
extern int            _DAT_004cec14   ; /* 004cec14 */
extern int            _DAT_004cec18   ; /* 004cec18 */
extern int            _DAT_004cec1c   ; /* 004cec1c */
extern int            _DAT_004cec20   ; /* 004cec20 */
extern int            _DAT_004cec24   ; /* 004cec24 */
extern int            _DAT_004cec40   ; /* 004cec40 */
extern int            _DAT_004cec44   ; /* 004cec44 */
extern int            _DAT_004cec48   ; /* 004cec48 */
extern int            _DAT_004cec4c   ; /* 004cec4c */
extern int            _DAT_004cecd0   ; /* 004cecd0 */
extern int            _DAT_004cecd4   ; /* 004cecd4 */
extern int            _DAT_004cecd8   ; /* 004cecd8 */
extern int            _DAT_004cecdc   ; /* 004cecdc */
extern int            _DAT_004cece0   ; /* 004cece0 */
extern int            _DAT_004cece4   ; /* 004cece4 */
extern int            _DAT_004cece8   ; /* 004cece8 */
extern int            _DAT_004ced20   ; /* 004ced20 */
extern int            _DAT_004ced24   ; /* 004ced24 */
extern int            _DAT_004ced28   ; /* 004ced28 */
extern int            _DAT_004ced2c   ; /* 004ced2c */
extern int            _DAT_004ced30   ; /* 004ced30 */
extern int            _DAT_004ced34   ; /* 004ced34 */
extern int            _DAT_004ced38   ; /* 004ced38 */
extern int            _DAT_004ced3c   ; /* 004ced3c */
extern int            _DAT_004ced40   ; /* 004ced40 */
extern int            _DAT_004ced44   ; /* 004ced44 */
extern int            _DAT_004ced48   ; /* 004ced48 */
extern int            _DAT_004ced58   ; /* 004ced58 */
extern int            _DAT_004ced5c   ; /* 004ced5c */
extern int            _DAT_004ced60   ; /* 004ced60 */
extern int            _DAT_004ced64   ; /* 004ced64 */
extern int            _DAT_004cedf8   ; /* 004cedf8 */
extern int            _DAT_004cedfc   ; /* 004cedfc */
extern int            _DAT_004cee00   ; /* 004cee00 */
extern int            _DAT_004cee04   ; /* 004cee04 */
extern int            _DAT_004cee08   ; /* 004cee08 */
extern int            _DAT_004cee0c   ; /* 004cee0c */
extern int            _DAT_004cee10   ; /* 004cee10 */
extern int            _DAT_004cee14   ; /* 004cee14 */
extern int            _DAT_004cee38   ; /* 004cee38 */
extern int            _DAT_004cee3c   ; /* 004cee3c */
extern int            _DAT_004cee48   ; /* 004cee48 */
extern int            _DAT_004cee5c   ; /* 004cee5c */
extern int            _DAT_004cee68   ; /* 004cee68 */
extern int            _DAT_004cee6c   ; /* 004cee6c */
extern int            _DAT_004cefbc   ; /* 004cefbc */
extern int            _DAT_004cefbe   ; /* 004cefbe */
extern int            _DAT_004cefc0   ; /* 004cefc0 */
extern int            _DAT_004cefc4   ; /* 004cefc4 */
extern int            _DAT_004cefc6   ; /* 004cefc6 */
extern int            _DAT_004cefc8   ; /* 004cefc8 */
extern int            _DAT_004cf0d8   ; /* 004cf0d8 */
extern int            _DAT_004cf0dc   ; /* 004cf0dc */
extern int            _DAT_004cf0e4   ; /* 004cf0e4 */
extern int            _DAT_004cf0e8   ; /* 004cf0e8 */
extern int            _DAT_004cf0f0   ; /* 004cf0f0 */
extern int            _DAT_004cf280   ; /* 004cf280 */
extern int            _DAT_004cf284   ; /* 004cf284 */
extern int            _DAT_004cf288   ; /* 004cf288 */
extern int            _DAT_004cf2a0   ; /* 004cf2a0 */
extern int            _DAT_004cf40c   ; /* 004cf40c */
extern int            _DAT_004cf410   ; /* 004cf410 */
extern int            _DAT_004cf414   ; /* 004cf414 */
extern int            _DAT_004cf430   ; /* 004cf430 */
extern int            _DAT_004cf438   ; /* 004cf438 */
extern int            _DAT_004cf440   ; /* 004cf440 */
extern int            _DAT_004cf448   ; /* 004cf448 */
extern int            _DAT_004cf450   ; /* 004cf450 */
extern int            _DAT_004cf458   ; /* 004cf458 */
extern int            _DAT_004cf46c   ; /* 004cf46c */
extern int            _DAT_004cf470   ; /* 004cf470 */
extern int            _DAT_004cf474   ; /* 004cf474 */
extern int            _DAT_004cf478   ; /* 004cf478 */
extern int            _DAT_004cf47c   ; /* 004cf47c */
extern int            _DAT_004cf480   ; /* 004cf480 */
extern int            _DAT_004cf484   ; /* 004cf484 */
extern int            _DAT_004cf488   ; /* 004cf488 */
extern int            _DAT_004cf48c   ; /* 004cf48c */
extern int            _DAT_004cf490   ; /* 004cf490 */
extern int            _DAT_004cf494   ; /* 004cf494 */
extern int            _DAT_004cf498   ; /* 004cf498 */
extern int            _DAT_004d0e68   ; /* 004d0e68 */
extern int            _DAT_004d4784   ; /* 004d4784 */
extern int            _DAT_004d4794   ; /* 004d4794 */
extern int            _DAT_004d4798   ; /* 004d4798 */
extern int            _DAT_004d479c   ; /* 004d479c */
extern int            _DAT_004d47ac   ; /* 004d47ac */
extern int            _DAT_004d47b0   ; /* 004d47b0 */
extern int            _DAT_004d47b4   ; /* 004d47b4 */
extern int            _DAT_004d47c4   ; /* 004d47c4 */
extern int            _DAT_004d47c8   ; /* 004d47c8 */
extern int            _DAT_004d47cc   ; /* 004d47cc */
extern int            _DAT_004d47dc   ; /* 004d47dc */
extern int            _DAT_004d47e0   ; /* 004d47e0 */
extern int            _DAT_004d47e4   ; /* 004d47e4 */
extern int            _DAT_004d47f4   ; /* 004d47f4 */
extern int            _DAT_004d47fc   ; /* 004d47fc */
extern int            _DAT_004d4800   ; /* 004d4800 */
extern int            _DAT_004d4810   ; /* 004d4810 */
extern int            _DAT_004d4814   ; /* 004d4814 */
extern int            _DAT_004d4818   ; /* 004d4818 */
extern int            _DAT_004d481c   ; /* 004d481c */
extern int            _DAT_004d482c   ; /* 004d482c */
extern int            _DAT_004d4830   ; /* 004d4830 */
extern int            _DAT_004d4834   ; /* 004d4834 */
extern int            _DAT_004d4838   ; /* 004d4838 */
extern int            _DAT_004d4848   ; /* 004d4848 */
extern int            _DAT_004d484c   ; /* 004d484c */
extern int            _DAT_004d4850   ; /* 004d4850 */
extern int            _DAT_004d4854   ; /* 004d4854 */
extern int            _DAT_004d4858   ; /* 004d4858 */
extern int            _DAT_004d485c   ; /* 004d485c */
extern int            _DAT_004d4860   ; /* 004d4860 */
extern int            _DAT_004d4868   ; /* 004d4868 */
extern int            _DAT_004d486c   ; /* 004d486c */
extern int            _DAT_004d4870   ; /* 004d4870 */
extern int            _DAT_004d4874   ; /* 004d4874 */
extern int            _DAT_004d4878   ; /* 004d4878 */
extern int            _DAT_004d4880   ; /* 004d4880 */
extern int            _DAT_004d4884   ; /* 004d4884 */
extern int            _DAT_004d4888   ; /* 004d4888 */
extern int            _DAT_004d488c   ; /* 004d488c */
extern int            _DAT_004d4890   ; /* 004d4890 */
extern int            _DAT_004d4898   ; /* 004d4898 */
extern int            _DAT_004d489c   ; /* 004d489c */
extern int            _DAT_004d48a0   ; /* 004d48a0 */
extern int            _DAT_004d48a4   ; /* 004d48a4 */
extern int            _DAT_004d48a8   ; /* 004d48a8 */
extern int            _DAT_004d48b0   ; /* 004d48b0 */
extern int            _DAT_004d48b4   ; /* 004d48b4 */
extern int            _DAT_004d48b8   ; /* 004d48b8 */
extern int            _DAT_004d48bc   ; /* 004d48bc */
extern int            _DAT_004d48c8   ; /* 004d48c8 */
extern int            _DAT_004d49d4   ; /* 004d49d4 */
extern int            _DAT_004d49dc   ; /* 004d49dc */
extern int            _DAT_004d49e0   ; /* 004d49e0 */
extern int            _DAT_004d49ec   ; /* 004d49ec */
extern int            _DAT_004d49f0   ; /* 004d49f0 */
extern int            _DAT_004d4f30   ; /* 004d4f30 */
extern int            _DAT_004d50c0   ; /* 004d50c0 */
extern int            _DAT_004d50c4   ; /* 004d50c4 */
extern int            _DAT_004d50c8   ; /* 004d50c8 */
extern int            _DAT_004d50cc   ; /* 004d50cc */
extern int            _DAT_004d6304   ; /* 004d6304 */
extern int            iRam00000000    ; /* 00000000 */
extern int            pcRam00000008   ; /* 00000008 */
extern int            uRam004cefc2    ; /* 004cefc2 */

#endif /* TH12_GLOBALS_H */
